apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base/ghost
configMapGenerator:
  - name: ghost-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true