apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ghost.fullname" . }}-migrate
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "ghost.fullname" . }}-migrate
      labels:
        {{- include "ghost.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ghost.serviceAccountName" . }}
      containers:
        - name: ghost-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh', '-c', 'ghost-mgr migrate || true']
          env:
            - name: url
              value: {{ .Values.ghost.url | quote }}
            - name: database__client
              value: {{ .Values.ghost.database.client | quote }}
            - name: database__connection__host
              value: {{ .Values.ghost.database.connection.host | quote }}
            - name: database__connection__port
              value: {{ .Values.ghost.database.connection.port | quote }}
            - name: database__connection__user
              value: {{ .Values.ghost.database.connection.user | quote }}
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: {{ include "ghost.fullname" . }}-db
                  key: password
            - name: database__connection__database
              value: {{ .Values.ghost.database.connection.database | quote }}
