apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.fullname" . }}-db
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
stringData:
  password: {{ .Values.ghost.database.connection.password | quote }}